### ISSUE TITLE
tests W3D3 failed

### ISSUE THREAD

**Issue by alkozp** [alkozp/WDX-180#1]
Tests for W3D3 failed, although file "completed-level.png" is exist

[CSS_SELECTORS](https://github.com/alkozp/WDX-180/actions/runs/6641511221/job/18069108338#step:3:8)
These files don't exist: user/week03/exercises/day03/completed-level.png

**Comment by asterisg** [comment]
After you've completed all the exercises and correctly named the file, all tests for exercises passed. If you do not submit all exercises, then the test will fail. We should fix that, so it's clear that each test refers to a specific exercises.

Sorry for any troubles caused @alkozp ! Keep up the good work!
